### ISSUE TITLE
Explore Jitsi Integration

### ISSUE THREAD

**Issue by anthonyrowe** [arenaxr/arena-web-core#323]
It appears that jitsi quality from the ARENA is lower than the quality of the Jitsi Meet web client.  This could be a function of various quality mode controls or perhaps the suggested camera parameters for WebRTC (constraints).  There are various other tuning parameters in Jitsi like EnableLayerSupression that we should explore (might contribute to reducing bandwidth on paused streams).  Adding a debug mechanism to easily see user upload quality (perhaps in AV select) would also help.

**Comment by mwfarb** [comment]
All features implemented since about late spring 2022.
