### ISSUE TITLE
Video Click to play problem

### ISSUE THREAD

**Issue by anthonyrowe** [arenaxr/arena-web-core#325]
It seems like videos don't play on click anymore.

Easy examples in public/lobby square_vid1 and in public/skatepark videoscreen2.  Videos do play if they are set to auto-start, so the video component must still be working.

**Comment by nampereira** [comment]
Think these are related: #285, #311.

Review video controls and possibly merge with jitsi-video.

**Comment by EdwardLu2018** [comment]
This has been fixed in 801688c780d28ca4f4adc3700c7bcc8556c04007
