### ISSUE TITLE
Location-based Triggers in XR

### ISSUE THREAD

**Issue by anthonyrowe** [arenaxr/arena-web-core#332]
We should add support for triggers when people get near locations and/or objects in an XR scene.  This would make it possible for applications to react accordingly when users moves into certain locations without manually tracking all user cameras. Imagine for example a welcome tutorial when you approach an area or a display that pops out of an object when you get near it. This could perhaps be done client-side with colliders in a-frame?  We likely want similar functionality to clicking on objects with events like enter, inside and exit.  These regions could be defined by polygons?  2D / 3D? It probably makes sense for these to be events that everyone can access.

**Comment by msrivastava** [comment]
I was thinking about privacy raminifications. Looking into the future, particularly in XR context, maybe we should allow for both public and private scenes: In the former, the geo-fence events are public which in the latter the people have to give permissions for others to access the events (may be XR scene owner will always have visibility to all events).

**Comment by hiliang-cmu** [comment]
> This could perhaps be done client-side with colliders in a-frame? We likely want similar functionality to clicking on objects with events like enter, inside and exit. These regions could be defined by polygons? 2D / 3D? It probably makes sense for these to be events that everyone can access.

Definitely some overlap with the "teleporter pad" area functionality that we had discussed in past, basically amounting to events that fire locally when zone collision first occurs -- for __simple__ geometries like boxes, spheres, and cylinders that would *not* require loading the entire aframe-physics engine. In so far as that we have existing client-side events that fire for clicking, we could have one for "enterzone", "exitzone".

**Comment by hi-liang** [comment]
We actually have AABB collisions as of a bit ago, these are far too coarse for like physics or something, but ideal for location zones.

The event is broadcast as a clientEvent like so, where `ids` are some box entities aligned to axes (probably invisible):

```
{
                object_id: <clientObj hand or camera id>,
                action: 'clientEvent',
                type: 'collision-start',
                data: {
                    source: <clientObj hand or camera id>,
                    position: <client hand/camera position>),
                    targets: [{
                        id: <target AABB objectID>,
                        position: <position of target AABB objectid>,
                    }]),
                },
            }
```
