### ISSUE TITLE
Can't click login in portrait mode in Safari on iOS

### ISSUE THREAD

**Issue by anthonyrowe** [arenaxr/arena-web-core#334]
Can we add some padding to the bottom of the AV selector login screen for mobile devices to make it easier (possible without rotating the phone) to press the login button?  Or maybe this is a feature to force landscape mode?

**Comment by hiliang-cmu** [comment]
Can you post a screenshot of the cutoff?

**Comment by EdwardLu2018** [comment]
I think it is fixed now? Should be ok to close this issue.
