### ISSUE TITLE
Quest 2 Goes to 0,0,0 when you switch to VR mode

### ISSUE THREAD

**Issue by anthonyrowe** [arenaxr/arena-web-core#359]
When you arrive in a scene, the quest goes to the right starting coordinate.  Once you click "VR" it jumps to the origin.  It does it on some browsers (Mike saw it once or twice on his machine, but we can't reproduce).

**Comment by EdwardLu2018** [comment]
Resolved in 206baa5319c48134afdc68c784ed880696d0fbf8
