### ISSUE TITLE
Video click does not work

### ISSUE THREAD

**Issue by nampereira** [arenaxr/arena-web-core#384]
**Describe the bug**
Clicking a video does not make it play, when before it used to. 

**To Reproduce**
Enter lobby scene, click video, nothing happens.

**Expected behavior**
Should start/plause the video.

**Comment by mwfarb** [comment]
Might be good to fix with #411

**Comment by EdwardLu2018** [comment]
Fixed in 4b69b6d. Aframe needs to check for a `cursorEl` in the `mousedown` event now.
