### ISSUE TITLE
Add easy scene export

### ISSUE THREAD

**Issue by mwfarb** [arenaxr/arena-web-core#415]
We have a way to import scenes in json from the file store on the build page. However it can be a heavy lift to copy scenes across servers, or into namespaces without established accounts.
- We have this: https://github.com/conix-center/ARENA-py/tree/master/tools/import-export-scenes
- Can we add an export button next to the import scene button on the build page?

**Comment by EdwardLu2018** [comment]
I think this has been a feature for a while now. Closing.
