### ISSUE TITLE
Click Source Position is not Correct in AR

### ISSUE THREAD

**Issue by EdwardLu2018** [arenaxr/arena-web-core#484]
**Describe the bug**
Click source position is not correct in AR.

**To Reproduce**
1. Go to some scene with a clickable object
2. Run python laser pointer program
3. Click on object
4. Laser's source position will not be updated to re-localized origin

**Comment by hi-liang** [comment]
https://github.com/arenaxr/arena-web-core/blob/2cb9f3734b92bb8b13b3a5aa871f1d4aea83953e/src/components/click-listener.js#L26-L40

Need to go through all these clientEvents and change the position from camera position to world position (factors in rig position/rotation offsets)

**Comment by mwfarb** [comment]
We still need both camera position and object intersection position right? Just that both will be in world coordinates after the change?

**Comment by hi-liang** [comment]
The intersection position comes from AFRAME I think, which should already be in world coordinates. The commit above just fixes the camera positions
