### ISSUE TITLE
armode=true camera permissions loading error

### ISSUE THREAD

**Issue by EdwardLu2018** [arenaxr/arena-web-core#492]
**Describe the bug**
Due to 048189ac236ff49a3e86010bd856fe2671ac4684, jitsi now loads __after__ armode=1 asks for camera permissions, and gives a black screen in webar/spotar mode with ?armode=1. 

**To Reproduce**
1. Go to any scene with ?armode=1
2. It will ask for camera permissions for webar, then camera permissions for jitsi, then the screen will be black. This is because the passthrough video feed gets overriden by jitsi. 

**Expected behavior**
Should maybe ask for jitsi camera permissions first, then webar?

**Comment by mwfarb** [comment]
I'll take a look at this tonight.

**Comment by mwfarb** [comment]
I just put this logic back the way it was for now.
