### ISSUE TITLE
Museum tags stopped working (probably URL parsing is broken?)

### ISSUE THREAD

**Issue by anthonyrowe** [arenaxr/arena-web-core#498]
Tags for the museum project are broken now.  Seems like spot AR mode in non-WebXR browsers doesn't work and anonymous login seems skipped.  For example on normal mobile browser, this used to work: https://arenaxr.org/agr/garden?armode=1&noreticle=1&auth=anonymous

**Comment by EdwardLu2018** [comment]
Should be fixed in dc12cf0534749e7a7cee50b74a63e9cd601ee163. Just needs to be released on arenaxr.org.

**Comment by EdwardLu2018** [comment]
Related to #492, which was patched by the commit above.
