### ISSUE TITLE
Chrome AR Click

### ISSUE THREAD

**Issue by mwfarb** [arenaxr/arena-web-core#515]
Now mouse-clicks aren't working in chrome AR.

ARENA Versions
Services stack	:v1.0.3
Core	:v1.14.1
Persist	:v1.0.2a
Account	:v1.1.1
Broker	:v1.6.10
Filestore	:v2.20.1
Orchestrator	:v1.1.0
Runtime Native	:v1.1.0
Init Utils	:v1.0.1

**Comment by mwfarb** [comment]
Chrome Browser on Android tablet.

**Comment by hi-liang** [comment]
I know it worked before but apparently this is how it's supposed to be by intentional design. 

AR **hit-tests** can be raycast from clicking anywhere on the screen,

but virtual objects have to be aimed and clicked now by reticle for chrome as well :(

**Comment by hi-liang** [comment]
Should be resolved as of c4a0cd4
