### ISSUE TITLE
Ensure all pubsub rotations are in quats

### ISSUE THREAD

**Issue by mwfarb** [arenaxr/arena-web-core#519]
Convert if needed, bad things happen without a `w`

We need to update the build page format and schema to only allow quaternions in wire message format. We can keep Euler on GUI for user readability.

Problem generalized to updating quat format with euler format, we end up mixing types and unit sizes and generating inaccuracy. Example:
1. Generate a `box` with quaternions rotation wire format = (0,0,0,1).
2. Update `box` in Python with `position=Position(0,45,0)`
3. Leaves wire rotation as (0,45,0,1) or (euler, euler, euler, quaternion)

Solution:
- Remove W as option from rotation schema.
- Allow GUI Euler for readability.
- Convert to quaternion before wire publish.
- Can leave Scene View rendering of incoming Euler wire format for backward compatibility.
- This is less straightforward on the build page since it tries to avoid special processing between wire format and GUI (perhaps needs a special euler edit box).

Related:
- https://github.com/arenaxr/arena-unity/issues/54
- https://github.com/arenaxr/arena-py/issues/125

**Comment by mwfarb** [comment]
@EdwardLu2018 @nampereira adding you to discussion with @johnchoi313 @hi-liang

**Comment by anthonyrowe** [comment]
Other option is adding a "Type" parameter that tells you the coordinate system that everyone should be checking / updating (even with merge updates just to be sure)

**Comment by mwfarb** [comment]
👍

**Comment by nampereira** [comment]
Web client relies on ['w' do distinguish quat from euler angles in degrees](https://github.com/arenaxr/arena-web-core/blob/275fa5e1b88da1daa5fd3522a97e9e45de7f512e/src/message-actions/create-update.js#L384). It should deal well with updates with `{x,y,z}` or `{x,y,z,w}`.

Seems that it really is an issue in persist where it cannot easily decide it should not merge `{x,y,z}` with `{x,y,z,w}`. Currently, the fix can be to add `{"overwrite": true}` to avoid merging.

**Comment by mwfarb** [comment]
Migrated wire format on build page to only use Quaternions: https://github.com/arenaxr/arena-web-core/commit/7ea52d39930e9f743f96d728ddb83fa41abf8f7f.
