### ISSUE TITLE
Build crashes trying to open public page for non-admin users

### ISSUE THREAD

**Issue by nampereira** [arenaxr/arena-web-core#558]
**Describe the bug**

When a non-admin user opens https://arenaxr.org/build

Build tries to get a default scene:
https://arenaxr.org/persist/public/default

This fails due to permissions, and build does not load.

**Note**: If we pass the `scene` parameter, this behaviour does not happen.

**To Reproduce**
Open https://arenaxr.org/build/ as a non-admin user.

It will be loading for a while:
![image](https://github.com/arenaxr/arena-web-core/assets/3504501/2118a6e4-ce22-428a-ba98-28fdc534e191)

Until it times out and: 
![image](https://github.com/arenaxr/arena-web-core/assets/3504501/1c5ca056-a798-4e8a-b5ab-e1c96a71deec)

**Expected behavior**
Loads a user scene, or an empty form, if user has no scenes.

**Device/OS (please complete the following information):**

-  Tried in chrome

**Comment by hi-liang** [comment]
Resolved w/ 2ed5f2b
