### ISSUE TITLE
Add custom field validators for build

### ISSUE THREAD

**Issue by hi-liang** [arenaxr/arena-web-core#584]
It's possible to input bad values into certain fields despite valid types. For instance, rotation takes number types but should be rangebound -- terms greater than 1 will mess up the scale of an object.

This seems like we can write some custom validators https://github.com/json-editor/json-editor#custom-validation

**Comment by mwfarb** [comment]
Using the standard json schema also works here: https://github.com/arenaxr/arena-web-core/commit/e4ab61c70ad5197178533fe0ee47dfd62d6a89ef

<img width="1349" alt="Screenshot 2023-12-08 at 2 30 18 PM" src="https://github.com/arenaxr/arena-web-core/assets/215994/9d569612-40c8-40e1-820d-975ec30524bf">
