### ISSUE TITLE
Arbitrary Tracker

### ISSUE THREAD

**Issue by mwfarb** [arenaxr/arena-web-core#602]
**Is your feature request related to a problem? Please describe.**
Optitrack tracker and other systems need a way to store generated ids and tags into persist similar to ARMarker. Suggestion by @johnchoi313.

**Describe the solution you'd like**
- addition of offset pose added to ARMarker.
- creation of ArbitraryTracker, including properties of pose offset, tag name, tag type.

**Describe alternatives you've considered**
Hoping for input from @ivan and @nampereira 

**Additional context**
Wanted to capture discussion between @johnchoi313 and @mwfarb

**Comment by hi-liang** [comment]
When we process Apriltags currently, we consider its offset pose the same as the (world) pose of the entity it is attached to, which allows for parenting too. I don't think there should be any reason why that can't be applicable to all marker types.

As far arbitrary tracker, we should probably just add more `markertypes` as they come up, as well as any extra more fields to ARMarker. If a specific marker type demands a bunch of custom fields very specific to it, we can maybe split it off to its own component.

**Comment by mwfarb** [comment]
Closed in https://github.com/arenaxr/arena-web-core/commit/b10385d81cafa7d63a2eb4f2e69d64f2540dd095
