### ISSUE TITLE
mqtt message localization is complete

### ISSUE THREAD

**Issue by mwfarb** [arenaxr/arena-web-core#681]
Add point clouds and detect when localization is complete.
Receive mqtt message localization is complete, state, per user. This is useful for avoiding multi user re localization of the scene

**Comment by hi-liang** [comment]
> Add point clouds 
What's this part

**Comment by mwfarb** [comment]
Point clouds was just a reference to one method students were using to align the scene, probably ancillary to the feature. As long as they have access to a "localization complete" message, I think they can manage any pre-alignment themselves.
