### ISSUE TITLE
Left/right arrow keys move user while writing chat message

### ISSUE THREAD

**Issue by mwfarb** [arenaxr/arena-web-core#89]

**Comment by nampereira** [comment]
I remember we talked about this some time ago. Not sure what to do. From my view, the user might want to actually move the cursor to edit the message. Unless i did not get the issue correctly.

**Comment by mwfarb** [comment]
I think that's right:
- When the cursor focus is in settings/chat popup input element, arrow keys should not move the camera.
- Otherwise arrow keys should move the camera as expected.

**Comment by EdwardLu2018** [comment]
Think I fixed this in 601115cc8730197a23d1ed4c0201e6165177319e.
Will keep this issue open in case this causes any problems.
